import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function portfolio() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={"grid"}>
        <Link href="https://www.druve.com.ng">
          <a className={"card"}>
            <h2>Druve &rarr;</h2>
            <p>Advertize Across WhatsApp Statuses</p>
          </a>
        </Link>
        <a href="https://www.ajebuta.com" className={"card"}>
          <h2>Ajebuta &rarr;</h2>
          <p>Connect customers to nearby service providers, professionals</p>
        </a>
      </div>
    </div>
  );
}
