import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function portfolio() {
  return (
    <div className={"container"}>
      <Head>
        <title>I am Dellyson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"main"}>
        <h1 className={"title"}>I am Dellyson</h1>

        <p className={"description"}>Projects I have worked on!</p>

        <div className={"grid"}>
          <Link href="https://www.druve.com.ng">
            <a className={"card"}>
              <h2>Druve &rarr;</h2>
              <p>Advertize Across WhatsApp Statuses</p>
            </a>
          </Link>
          <a href="https://www.ajebuta.com" className={"card"}>
            <h2>Ajebuta &rarr;</h2>
            <p>Connect customers to nearby service providers, professionals</p>
          </a>
        </div>
      </main>

      <footer className={"footer"}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={"logo"}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
