import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>I am Dellyson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"main"}>
        <h1 className={"title"}>I am Dellyson</h1>
        <p className={"description"}>Welcome to my website!</p>
        <div className={"grid"}>
          <article className={"styles"}>
            <h1>A little information about me</h1>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              Dignissimos dolorem suscipit corrupti voluptas quod maiores amet
              velit, consequatur ipsam distinctio.
            </p>
          </article>
        </div>
      </main>
    </div>
  );
}
